title: Aya's Blog
author: salamaaya
email: asalama0214@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello and welcome! My name is Aya Salama, a senior graduating from EBHS. This site is meant to show a glimpse of my life!

# social links
twitter_username: i don't use twitter
github_username:  salamaaya

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
